### ISSUE TITLE
Logical errors

### ISSUE THREAD

**Issue by kamilsft** [davidhanna123/SmartStudyScheduler#16]
• Problem Report Number: kg1
• Who does this code concern: Yadon (Event scheduling Functionality) 
• Reported By:  Kamil Ginyatov
• Date Reported: 2024/03/23
• Program Name: Event Scheduling Logic
• Release Number: 1
• Version: (build)
• Configurations: Java Application Environment
• Report Type: Coding Bug
• Can Reproduce: Yes
• Severity: Medium
• Priority: Medium
• Problem Summary: Logical errors and not fully done checks in event scheduling function
• Key words: Null check, date comparison, time comparison, infinite loop

• Problem Description and How to Reproduce it:
• Redundant Null Check: The condition “if(minEventDate.getValue() == null || minEventDate.getValue() == null)” checks minEventDate.getValue() twice instead of checking both minEventDate.getValue() and maxEventDate.getValue(). 
Steps to fix it: 
Leave maxEventDate as null and set minEventDate
• Status: Open
• Resolution: The project manager owns this
• Resolved by: Not Yet

**Comment by YadonKS** [comment]
The typo was fixed and now both max and min date are checked.
