### ISSUE TITLE
Logical Error when auto scheduling

### ISSUE THREAD

**Issue by kamilsft** [davidhanna123/SmartStudyScheduler#17]
• Problem Report Number: kg2
• Who does this code concern: Yadon (Event scheduling Functionality) 
• Reported By:  Kamil Ginyatov
• Date Reported: 2024/03/23
• Program Name: Event Scheduling Logic
• Release Number: 1
• Version: (build)
• Configurations: Java Application Environment
• Report Type: Coding Bug
• Can Reproduce: Yes
• Severity: Medium
• Priority: High
• Problem Summary: Logical errors when auto-scheduling 
• Key words: event scheduling, iteration over dates, boundaries check

• Problem Description and How to Reproduce it:
• The code which is designed to set up events doesn't work right if the start and end dates are in different months or years. It looks like it only checks within the same month and year. This means if you try to schedule an event that begins in one month and ends in the next or over the new year, it won't schedule properly. 
Steps to fix it: 
Change the code so it can handle events that go from one month to another or from one year to the next. It should look at every day between the start and end date, even if those dates are in different months or years, to make sure the event can be scheduled for the correct times. 
• Status: Open
• Resolution: The project manager owns this
• Resolved by: Not Yet

**Comment by YadonKS** [comment]
Suggestion followed. Two more methods were added to cover cases where the time gap is between different years or within the same year and between different months. The methods are in the GuiControllerHelper.java file.
