### ISSUE TITLE
Potential Infinite Loop

### ISSUE THREAD

**Issue by kamilsft** [davidhanna123/SmartStudyScheduler#18]
• Problem Report Number: kg3
• Who does this code concern: Yadon (Event scheduling Functionality) 
• Reported By:  Kamil Ginyatov
• Date Reported: 2024/03/23
• Program Name: Event Scheduling Logic
• Release Number: 1
• Version: (build)
• Configurations: Java Application Environment
• Report Type: Coding Bug
• Can Reproduce: Yes
• Severity: Medium
• Priority: Medium
• Problem Summary: Potential Infinite loop 
• Key words: time slot search, infinite loop
• Potential Infinite Loop: If a suitable time slot is not found, the loop will keep looking for the spot which doesn't exist.   
Steps to fix it: 
Provide conditions that make it impossible to schedule the event within the given criteria
• Status: Open
• Resolution: The project manager owns this
• Resolved by: Not Yet

**Comment by YadonKS** [comment]
A for each loop was used so I am not sure how an infinite loop was triggered. Error not replicable...please send steps of how to replicate issue @kamilsft

**Comment by kamilsft** [comment]
The infinite loop isn't triggered, but it might trigger in certain conditions . What if there is no slot that fits our requirements ? The code will just keep looking for the spot without realizing that it might not exist . For instance, if a time slot is taken and you want to add a slop, then the loop will just keep searching. 
Steps to fix:  before entering a loop, add a check to see if there are any available slots  that meet the criteria.  If no slots available you can notify a user.

**Comment by YadonKS** [comment]
I added an error message that would notify the user. Let me know if you encounter the issue again.
