### ISSUE TITLE
Long Method

### ISSUE THREAD

**Issue by kamilsft** [davidhanna123/SmartStudyScheduler#19]
Code Smell Name: Long Method
**Suggestion For**: Yadon
**Suggestion From**: Kamil
**File Name**: HomeController.java
**Issue Description**: schedule.setOnAction is long with nested loops.
**Suggested Solution**: refactor the code to reduce complexity.

**Comment by YadonKS** [comment]
Suggestion followed. 2 new classes created: ScheduleInputComponents is a group of input gui components for the scheduling method and  ScheduleOutputComponents is a group of output components for the scheduling method. These classes are used as inputs for a new interface that contains methods for helping the gui carry out complex scheduling and other tasks. 

![image](https://github.com/davidhanna123/SmartStudyScheduler/assets/127888836/0aa019cf-40a4-424c-a5a3-aebe3a1507e4)
