### ISSUE TITLE
Duration field accepts negative, zero, and unrealistically large numbers

### ISSUE THREAD

**Issue by davidhanna123** [davidhanna123/SmartStudyScheduler#6]
Problem report number: dh6
Who does this concern: Jonah.
Reported by: David Hanna
Date reported: 03/23/2024
Program (or component) name: Homework and Assignment Adding
Release number: 2
Version (build) identifier: itr2
Configuration(s): HW and SW configurations: JDK 11 / Integrated Development Environment: IntelliJ IDEA / Eclipse IDE / JavaFX Library: JavaFX SDK 11 / Database System: PostgreSQL
Report type: coding bug.
Can reproduce: yes.
Severity: Medium.
Priority: assigned by devs/proj. manager.
Problem summary: duration field accepts all integers which fail to take into account any unrealistic entries that wouldn't make logical sense.
How to reproduce it: click on: Add Event -> Add Homework -> yes -> enter a negative, zero, or an unrealistically large number for duration -> Enter.
Suggested fix: modify isInt to reject integers <=0 and > a given max value by the developer, and output an error message when these terms are violated.

**Comment by 218945030** [comment]
Modified isInt to reject integers less than or equal to zero and greater than 31. Also added appropriate error message.
