### ISSUE TITLE
Missing exception handling for invalid dates

### ISSUE THREAD

**Issue by davidhanna123** [davidhanna123/SmartStudyScheduler#7]
Problem report number: dh7
Who does this concern: Jonah.
Reported by: David Hanna
Date reported: 03/23/2024
Program (or component) name: Assignment Adding
Release number: 2
Version (build) identifier: itr2
Configuration(s): HW and SW configurations: JDK 11 / Integrated Development Environment: IntelliJ IDEA / Eclipse IDE / JavaFX Library: JavaFX SDK 11 / Database System: PostgreSQL
Report type: coding bug.
Can reproduce: yes.
Severity: High.
Priority: assigned by devs/proj. manager.
Problem summary: errors are displayed in the console, throws java.time.DateTimeException. No error message on the window.
How to reproduce it: click on: Add Event -> Add Homework -> yes -> enter an invalid date in month, day, year -> Enter.
Suggested fix: add exception handling to catch these exceptions and add an error message on the window.

**Comment by 218945030** [comment]
Replacing old input method of date parameters with a javafx date picker fixes this issue
